FROM redis:alpine

COPY config/redis.conf /usr/local/etc/redis.conf

EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

#docker build -t redis:latest -f ./jenkinsconf/Dockerfile.redis .
#docker run -it -d --name redis --restart=always
