FROM redis:alpine

ARG REDIS_PASS=$REDIS_PASS

COPY config/redis.conf /usr/local/etc/redis/redis.conf
RUN echo "requirepass ${REDIS_PASS}" >> /usr/local/etc/redis/redis.conf
EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

#docker build -t redis:latest -f ./jenkinsconf/Dockerfile.redis .
#docker run -it -d --name redis --restart=always -p 6379:6379 redis:latest
